<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <style>
        * { box-sizing: border-box; }
        body { font-family: DejaVu Sans, sans-serif; margin: 0; padding: 24px; color: #1e293b; }
        .frame { border: 4px solid #4a148c; border-radius: 12px; padding: 28px 36px; min-height: 420px; position: relative; }
        .ribbon { position: absolute; top: 18px; right: 24px; font-size: 11px; font-weight: 700; color: #4a148c; letter-spacing: .12em; text-transform: uppercase; }
        h1 { text-align: center; font-size: 26px; margin: 12px 0 8px; color: #4a148c; }
        .sub { text-align: center; font-size: 13px; color: #64748b; margin-bottom: 28px; }
        .hospital { text-align: center; font-size: 14px; font-weight: 700; color: #0f172a; margin-bottom: 4px; }
        .present { text-align: center; font-size: 15px; margin: 28px 0 8px; color: #334155; }
        .name { text-align: center; font-size: 22px; font-weight: 700; color: #0f172a; margin-bottom: 24px; }
        .meta { width: 100%; border-collapse: collapse; margin-top: 16px; font-size: 12px; }
        .meta td { padding: 6px 8px; border-bottom: 1px solid #e2e8f0; }
        .meta td:first-child { color: #64748b; width: 32%; font-weight: 600; }
        .certno { margin-top: 28px; text-align: center; font-size: 11px; color: #64748b; }
        .footer { margin-top: 20px; text-align: center; font-size: 10px; color: #94a3b8; }
    </style>
</head>
<body>
<div class="frame">
    <div class="ribbon">CPD / Training</div>
    <div class="hospital">{{ $hospitalName }}</div>
    <h1>Certificate of Completion</h1>
    <div class="sub">{{ $programTitle }}@if(!empty($category)) — {{ $category }}@endif</div>
    <div class="present">This is to certify that</div>
    <div class="name">{{ $participantName }}</div>
    <div class="present" style="font-size:13px">has successfully completed the above training programme on <strong>{{ $scheduleDate ?? '—' }}</strong>@if(!empty($venue)) at <strong>{{ $venue }}</strong>@endif@if(!empty($durationHours)) ({{ $durationHours }} hours)@endif.</div>
    <table class="meta">
        <tr><td>Certificate no.</td><td>{{ $certificateNumber }}</td></tr>
        <tr><td>Issued on</td><td>{{ $issuedDate }}</td></tr>
    </table>
    <div class="certno">Verify this document with your HR department. System-generated document.</div>
    <div class="footer">Generated by HR Training &amp; CPD module</div>
</div>
</body>
</html>
